// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ClientDashboard(username string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Client Dashboard - FreelanceFi</title><link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\"></head><body class=\"vh-100\"><div class=\"d-flex h-100\"><!-- Sidebar --><div class=\"bg-dark text-white p-3\" style=\"width: 250px;\"><h2 class=\"text-center mb-4\">FreelanceFi</h2><ul class=\"nav flex-column\"><li class=\"nav-item mb-2\"><a class=\"nav-link text-white\" href=\"/home\">Home</a></li><li class=\"nav-item mb-2\"><a class=\"nav-link text-white\" href=\"/client/my-tasks\">My Tasks</a></li><li class=\"nav-item mb-2\"><a class=\"nav-link text-white\" href=\"/client/bids\">View Bids</a></li><li class=\"nav-item mt-4\"><a class=\"btn btn-secondary w-100\" href=\"/\">Logout</a></li></ul></div><!-- Main Content --><div class=\"flex-grow-1 d-flex justify-content-center align-items-center bg-light\"><div class=\"card p-5 shadow-lg text-center\"><h1 class=\"mb-4\">Welcome, <strong>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(username)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/client/dashboard.templ`, Line: 37, Col: 59}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</strong>!</h1><p class=\"mb-4\">You are logged in as a <strong>client</strong>.</p><p class=\"mb-4\">You can post tasks and manage your projects.</p><a href=\"/client/my-tasks\" class=\"btn btn-primary w-100\">Go to My Tasks</a></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
