// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.Int4      `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	Role         string           `json:"role"`
}
